# Generated by Django 6.0.7 on 2026-07-17 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuva', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='principal_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='application_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='repayment',
            old_name='amount_paid',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='repayment',
            old_name='repayment_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='remaining_balance',
        ),
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='alt_phone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='recorded_by',
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='yuva.member')),
            ],
        ),
        migrations.DeleteModel(
            name='Savings',
        ),
    ]
