# Generated by Django 6.0.7 on 2026-07-20 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuva', '0004_document_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='repayment',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='tenure_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuva.member'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuva.member'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuva.member'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuva.loan'),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuva.member'),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=10),
        ),
    ]
