# Generated by Django 6.0.7 on 2026-07-21 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuva', '0006_loaninstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('user', 'User')], default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='yuva.member'),
        ),
    ]
