# Generated by Django 6.0.7 on 2026-08-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuva', '0012_alter_attendancerecord_status_meeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Tracks whether the fine has been settled/paid'),
        ),
    ]
