# Generated by Django 6.0.7 on 2026-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuva', '0013_attendancerecord_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
