# Generated by Django 6.0.7 on 2026-08-07 08:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuva', '0014_rentalitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalitem',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='rental_price',
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='deposit_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rentals/'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='rental_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='yuva.rentalitem')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='yuva.member')),
            ],
        ),
    ]
