# Generated by Django 6.0.7 on 2026-07-25 05:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuva_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='member',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(default='Admin User', max_length=150),
        ),
        migrations.AddField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Warning', 'Warning'), ('Defaulter', 'Defaulter')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('RECOVERY', 'Recovery'), ('DEBIT', 'Debit')], default='CREDIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='credit_grade',
            field=models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C'), ('D', 'Grade D')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('purpose', models.CharField(max_length=255)),
                ('apply_date', models.DateField(default=django.utils.timezone.now)),
                ('disbursal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDERWRITING', 'Underwriting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20)),
                ('portfolio_status', models.CharField(choices=[('PERFORMING', 'Performing'), ('SUB_STANDARD', 'Sub-Standard'), ('DOUBTFUL', 'Doubtful'), ('LOSS', 'Loss')], default='PERFORMING', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='yuva_admin.member')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='yuva_admin.loanapplication'),
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
