# Generated by Django 6.0.7 on 2026-08-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuva_admin', '0003_attendancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='member',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='loan',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='LoanApplication',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
